# Changes here will be overwritten by Copier.
_commit: 1.7.1
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2021'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC
insiders: false
project_description: A legacy Python handler for mkdocstrings.
project_name: mkdocstrings-python (legacy)
python_package_command_line_name: ''
python_package_distribution_name: mkdocstrings-python-legacy
python_package_import_name: mkdocstrings_handlers
repository_name: python-legacy
repository_namespace: mkdocstrings
repository_provider: github.com

