# Changes here will be overwritten by Copier
_commit: 0.9.2
_src_path: gh:pawamoy/copier-pdm
author_email: pawamoy@pm.me
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2021'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: pawamoy@pm.me
copyright_license: ISC License
project_description: A legacy Python handler for mkdocstrings.
project_name: mkdocstrings-python (legacy)
python_package_command_line_name: mkdocstrings-python-legacy
python_package_distribution_name: mkdocstrings-python-legacy
python_package_import_name: mkdocstrings
repository_name: python-legacy
repository_namespace: mkdocstrings
repository_provider: github.com
use_precommit: false

