site_name: "mkdocstrings-python (legacy)"
site_description: "A legacy Python handler for mkdocstrings."
site_url: "https://mkdocstrings.github.io/python-legacy"
repo_url: "https://github.com/mkdocstrings/python-legacy"
repo_name: "mkdocstrings/python-legacy"
site_dir: "site"
watch: [mkdocs.yml, README.md, CONTRIBUTING.md, CHANGELOG.md, src/mkdocstrings_handlers]
copyright: Copyright &copy; 2021 Timothée Mazzucotelli
edit_uri: edit/main/docs/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
- Home:
  - Overview: index.md
  - Usage: usage.md
  - Changelog: changelog.md
  - Credits: credits.md
  - License: license.md
- API reference: reference.md
- Development:
  - Contributing: contributing.md
  - Code of Conduct: code_of_conduct.md
  - Coverage report: coverage.md
- mkdocstrings: https://mkdocstrings.github.io/

theme:
  name: material
  custom_dir: docs/.overrides
  icon:
    logo: material/currency-sign
  features:
  - announce.dismiss
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: lime
    toggle:
      icon: material/weather-night
      name: Switch to system preference

extra_css:
- css/material.css
- css/mkdocstrings.css

extra_javascript:
- js/feedback.js

markdown_extensions:
- attr_list
- admonition
- callouts
- footnotes
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- pymdownx.magiclink
- pymdownx.snippets:
    base_path: [!relative $config_dir]
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- toc:
    permalink: "¤"

plugins:
- search
- markdown-exec
- coverage
- mkdocstrings:
    handlers:
      python:
        import:
        - https://docs.python.org/3/objects.inv
        - https://mkdocstrings.github.io/objects.inv
        - https://mkdocstrings.github.io/pytkdocs/objects.inv
        paths: [src, docs]
        options:
          docstring_section_style: list
          filters: ["!^_"]
          group_by_category: true
          heading_level: 1
          inherited_members: true
          merge_init_into_class: true
          separate_signature: true
          show_category_heading: true
          show_root_heading: true
          show_root_full_path: false
          show_signature_annotations: true
          show_source: true
          show_submodules: false
          signature_crossrefs: true
          summary: true
- git-revision-date-localized:
    enabled: !ENV [DEPLOY, false]
    enable_creation_date: true
    type: timeago
- minify:
    minify_html: !ENV [DEPLOY, false]
- group:
    enabled: !ENV [MATERIAL_INSIDERS, false]
    plugins:
    - typeset

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/pawamoy
  - icon: fontawesome/brands/mastodon
    link: https://fosstodon.org/@pawamoy
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/pawamoy
  - icon: fontawesome/brands/gitter
    link: https://gitter.im/python-legacy/community
  - icon: fontawesome/brands/python
    link: https://pypi.org/project/mkdocstrings-python-legacy/
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: Let us know how we can improve this page.
